CREATE TABLE IF NOT EXISTS homepage_layout (
  id INT AUTO_INCREMENT PRIMARY KEY,
  layout_key VARCHAR(64) NOT NULL UNIQUE,
  config_json JSON NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
