/**
 * Sitemap Configuration Guide
 *
 * This application uses Next.js 14+ built-in sitemap generation.
 *
 * STATIC SITEMAP: app/sitemap.js
 * - Auto-generated by Next.js
 * - Located at /sitemap.xml
 * - Includes static pages and dynamic database content
 *
 * ROBOTS.TXT: app/robots.js
 * - Auto-generated by Next.js
 * - Located at /robots.txt
 * - Points search engines to the sitemap
 *
 * API ENDPOINT: /api/public/sitemap?type=articles|categories|all
 * - Detailed sitemap generation per content type
 * - Includes pagination support
 * - Useful for debugging and custom implementations
 *
 * SITEMAP STRUCTURE:
 *
 * 1. Static Pages (priority 1.0 - 0.5):
 *    - Home page (priority: 1.0, daily)
 *    - Categories page (priority: 0.9, weekly)
 *    - Latest articles (priority: 0.9, daily)
 *    - Info pages: about-us, privacy-policy, terms, etc. (priority: 0.5-0.7, monthly)
 *
 * 2. Dynamic Articles (priority 0.7, weekly):
 *    - Individual article pages
 *    - Last modified from database updated_at field
 *    - Includes featured image in sitemap
 *
 * 3. Dynamic Categories (priority 0.75, weekly):
 *    - Individual category pages
 *    - Filtered by parent_id IS NULL (top-level categories only)
 *    - Last modified from database
 *
 * PAGINATION:
 * - Dynamic content: Limited to 50,000 URLs per sitemap
 * - Multiple sitemaps generated if needed
 * - Query parameters for pagination: ?page=1, ?page=2, etc.
 *
 * PERFORMANCE NOTES:
 * - Sitemaps are cached for 1 hour (3600 seconds)
 * - Stale-while-revalidate: 24 hours for background updates
 * - Database queries optimized with SELECT limits
 *
 * TESTING:
 * - Visit /sitemap.xml to view main sitemap
 * - Visit /robots.txt to view robots configuration
 * - Visit /api/public/sitemap?type=articles for articles only
 * - Visit /api/public/sitemap?type=categories for categories only
 *
 * IMPORTANT: Update NEXT_PUBLIC_SITE_URL in .env.local
 * Example: NEXT_PUBLIC_SITE_URL=https://yoursite.com
 */

export const metadata = {
  title: "Sitemap Configuration",
  description: "Information about the sitemap and SEO configuration",
};

export default function SitemapConfig() {
  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-950 p-8">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl font-bold mb-8">Sitemap Configuration</h1>

        <div className="space-y-6">
          <section className="bg-white dark:bg-gray-900 rounded-lg p-6">
            <h2 className="text-2xl font-bold mb-4">📍 Available Sitemaps</h2>
            <ul className="space-y-2">
              <li>
                <a
                  href="/sitemap.xml"
                  className="text-blue-600 hover:underline"
                >
                  /sitemap.xml
                </a>{" "}
                - Main sitemap with all content
              </li>
              <li>
                <a href="/robots.txt" className="text-blue-600 hover:underline">
                  /robots.txt
                </a>{" "}
                - Search engine crawling rules
              </li>
            </ul>
          </section>

          <section className="bg-white dark:bg-gray-900 rounded-lg p-6">
            <h2 className="text-2xl font-bold mb-4">🔗 API Endpoints</h2>
            <div className="space-y-2">
              <p>
                <code className="bg-gray-100 dark:bg-gray-800 px-2 py-1 rounded">
                  /api/public/sitemap?type=all
                </code>{" "}
                - All content types
              </p>
              <p>
                <code className="bg-gray-100 dark:bg-gray-800 px-2 py-1 rounded">
                  /api/public/sitemap?type=articles
                </code>{" "}
                - Articles only
              </p>
              <p>
                <code className="bg-gray-100 dark:bg-gray-800 px-2 py-1 rounded">
                  /api/public/sitemap?type=categories
                </code>{" "}
                - Categories only
              </p>
            </div>
          </section>

          <section className="bg-white dark:bg-gray-900 rounded-lg p-6">
            <h2 className="text-2xl font-bold mb-4">⚙️ Configuration</h2>
            <p className="mb-4">Update your .env.local file:</p>
            <code className="bg-gray-100 dark:bg-gray-800 p-4 rounded block">
              NEXT_PUBLIC_SITE_URL=https://yoursite.com
            </code>
          </section>

          <section className="bg-blue-50 dark:bg-blue-950 rounded-lg p-6">
            <h2 className="text-2xl font-bold mb-4">✅ Features</h2>
            <ul className="space-y-2">
              <li>✓ Static pages included</li>
              <li>✓ Dynamic content from database</li>
              <li>✓ Automatic pagination support</li>
              <li>✓ Image sitemaps for articles</li>
              <li>✓ Last modified tracking</li>
              <li>✓ Priority-based URLs</li>
              <li>✓ Change frequency indicators</li>
              <li>✓ SEO optimized</li>
            </ul>
          </section>
        </div>
      </div>
    </div>
  );
}
